### ISSUE TITLE
Issue status

### ISSUE THREAD

**Issue by theosotr** [dspinellis/gi#12]
The status of an issue i.e. `open`, `closed` is part of issue tags. Should a "status" field be created which
will include the aforementioned values?

**Comment by dspinellis** [comment]
Having `open` and `closed` as tags allows the more general tags mechanism to be reused and also allows the issue's workflow to be expanded by adding more tags.  What would be the advantages of a `status` field?

**Comment by theosotr** [comment]
Yes you are right.

I was thinking of a distinction between them, just like Github does (status and labels). Moreover, it may be useful for filtering issues. For example, list open issues with `A` and `B` tags.
