### ISSUE TITLE
gi bash completion

### ISSUE THREAD

**Issue by iridakos** [dspinellis/gi#20]
## Summary
It would be very convenient to provide bash completion like the one git provides with the [git-completion script](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash).
### Sub-command auto-completion

Pressing the `tab` key just after the `gi` command, the script could show the available sub-commands:
```bash
$ gi <tab here>
assign    comment list  push
attach    edit    log   show
clone     git     new   tag
close     init    pull  watcher
```
Pressing the `tab` key after typing at least one character, it could show the available sub-commands starting with the given input (if any):
```bash
$ gi a<tab here>
assign attach
```
Of course, if there's only one command starting with the given input, it should be auto-completed immediately without displaying the single-element sub-command list.

### Issue/Comment SHA auto-completion

*This section applies only to the commands which accept issue/comment SHA argument.*

Pressing the `tab` key just after a sub-command, it should display a list of issue SHAs.
```bash
$ gi show <tab here>
5a955af f07b9b6 f77adec 
```
Of course, the issue SHAs should be filtered to those applicable for the given sub-command:

* the auto-complete list for `show`, `comment`, `tag`, `assign`, `attach`, `watcher` sub-commands should contain the SHAs of all issues.
* the auto-complete list for an `edit` sub-command should contain only SHAs of issues tagged as `open` or of comments of such issues.
* the auto-complete list for a `close` sub-command should contain only issues tagged as `open`.

**Note:** If it is feasible, it would be great if we could display the list of the SHAs as a **two columned** list allowing users to view a portion of the summary of the issue.
```bash
$ gi show <tab here>
5a955af Allow list subcommand to sup...
f07b9b6 Implement the issue SHA auto...
f77adec Sub-command auto-completion...
```

### Sub-command auto-completion

The available sub-commands will not be fixed in the script but they will be calculated dynamically from the output of the `gi` command execution without arguments. *It is important to preserve the current format of the output in future releases or update the auto-completion script accordingly.*

### Issue/Comment auto-completion

The `list` sub-command provides most of the desired output to be used in this context.
New functionality might be required for the comment's SHA (something like `gi list -c`) and can be further discussed during the implementation of the issue.

### Assignee
I could work on this if you believe it's a desired feature.

**Comment by dspinellis** [comment]
I like it, thank you for the very complete proposal!  Regarding sub-commands, I suggest abstracting their display into a function that can be used both for help and for input to the auto-completion script.
