### ISSUE TITLE
Usability: one typo away from git?

### ISSUE THREAD

**Issue by Hunter-Github** [dspinellis/gi#6]
`gi init`

vs.

`git init`

The probability of doing the wrong thing (TM) goes up with the number of times people use `gi`.

Suggestion: convert the script into a git plugin with a bit more verbose (but discoverable) name:

`git issue init`

or

`git issues init`

**Comment by dspinellis** [comment]
:+1:

**Comment by strk** [comment]
Try this:
```
git config --global alias.issue '!'"${PATH_TO}/gi"
```

**Comment by dspinellis** [comment]
So the best-practice implementation would be to 
* [ ] rename gi to git-issue, 
* [ ] adjust the documentation, and 
* [ ] recommend the alias configuration.

Right?

**Comment by strk** [comment]
Yes, sounds right
I'm basically just looking what git-appraise does about it...
